#include <stdlib.h>
#include <float.h>
#include "getIt.h"
#include "../../Unity/src/unity.h"

void setUp(void) {
    // set stuff up here
    //This will run at the beginning of every tests so you can put common code here
}

void tearDown(void) {
    // clean stuff up here
    //This will run at the end of every test so you can do common clean up here
}

void empty_input(void) {
  // nothing but eol
  char* expected = "";
  int length = 0;
  char actual[0];
  int flag = getIt(actual, &length);
  TEST_ASSERT_EQUAL_INT(flag, -1);
  TEST_ASSERT_EQUAL_STRING(expected, actual);
}

// void zero_length_input(void) {        //unfailable
//   // just /0
//   char * expected = "";
//   int length = 64;
//   char actual[length];
//   int flag = getIt(actual, &length);
//   TEST_ASSERT_EQUAL_INT(flag, 1);
//   TEST_ASSERT_EQUAL_STRING(expected, actual);

// }

// void big_input(void) {               //Redundant?
//   // inputs that will be truncated
//   char * expected = "";
// }

void giant_input(void) {
  // stuff a novel in there, see what happens
  char * expected = "BeeMovieScriptDialogueTranscriptVoilaFinallytheBeeMoviescriptish"; //64 characters of the string below
  // string to be input via command line BeeMovieScriptDialogueTranscriptVoilaFinallytheBeeMoviescriptishereforallyoufansoftheJerrySeinfeldanimatedmovieThispuppyisatranscriptthatwaspainstakinglytranscribedusingthescreenplayandorviewingsofthemovietogetthedialogueIknowIknowIstillneedtogetthecastnamesinthereandallthatjazzsoifyouhaveanycorrectionsfeelfreetodropmealineAtleastyoullhavesomeBeeMoviequotesorevenamonologueortwotoannoyyourcoworkerswithinthemeantimerightAndswingonbacktoDrewsScriptORamaafterwardsbecausereadingisgoodforyournoodleBetterthanFarmvilleanywayBeeMovieScriptAccordingtoallknownlawsofaviationthereisnowayabeeshouldbeabletoflyItswingsaretoosmalltogetitsfatlittlebodyoffthegroundThebeeofcoursefliesanywaybecausebeesdontcarewhathumansthinkisimpossibleYellowblackYellowblackYellowblackYellowblackOohblackandyellowLetsshakeitupalittleBarryBreakfastisreadyOomingHangonasecondHelloBarryAdamOanyoubelievethisishappeningIcantIllpickyouupLookingsharpUsethestairsYourfatherpaidgoodmoneyforthoseSorryImexcitedHeresthegraduateWereveryproudofyousonAperfectreportcardallBsVeryproudMaIgotathinggoinghereYougotlintonyourfuzzOwThatsmeWavetousWellbeinrow118000ByeBarryItoldyoustopflyinginthehouseHeyAdamHeyBarryIsthatfuzzgelAlittleSpecialdaygraduationNeverthoughtIdmakeitThreedaysgradeschoolthreedayshighschoolThosewereawkwardThreedayscollegeImgladItookadayandhitchhikedaroundthehiveYoudidcomebackdifferentHiBarryArtiegrowingamustacheLooksgoodHearaboutFrankieYeahYougoingtothefuneralNoImnotgoingEverybodyknowsstingsomeoneyoudieDontwasteitonasquirrelSuchahotheadIguesshecouldhavejustgottenoutofthewayIlovethisincorporatinganamusementparkintoourdayThatswhywedontneedvacationsBoyquiteabitofpompunderthecircumstancesWellAdamtodaywearemenWeareBeemenAmenHallelujahStudentsfacultydistinguishedbeespleasewelcomeDeanBuzzwellWelcomeNewHiveOitygraduatingclassof915ThatconcludesourceremoniesAndbeginsyourcareeratHonexIndustriesWillwepickourjobtodayIhearditsjustorientationHeadsupHerewegoKeepyourhandsandantennasinsidethetramatalltimesWonderwhatitllbelikeAlittlescaryWelcometoHonexadivisionofHonescoandapartoftheHexagonGroupThisisitWowWowWeknowthatyouasabeehaveworkedyourwholelifetogettothepointwhereyoucanworkforyourwholelifeHoneybeginswhenourvaliantPollenJocksbringthenectartothehiveOurtopsecretformulaisautomaticallycolorcorrectedscentadjustedandbubblecontouredintothissoothingsweetsyrupwithitsdistinctivegoldenglowyouknowasHoneyThatgirlwashotShesmycousinSheisYeswereallcousinsRightYourerightAtHonexweconstantlystrivetoimproveeveryaspectofbeeexistenceThesebeesarestresstestinganewhelmettechnologyWhatdoyouthinkhemakesNotenoughHerewehaveourlatestadvancementtheKrelmanWhatdoesthatdoOatchesthatlittlestrandofhoneythathangsafteryoupouritSavesusmillionsOananyoneworkontheKrelmanOfcourseMostbeejobsaresmallonesButbeesknowthateverysmalljobifitsdonewellmeansalotButchoosecarefullybecauseyoullstayinthejobyoupickfortherestofyourlifeThesamejobtherestofyourlifeIdidntknowthatWhatsthedifferenceYoullbehappytoknowthatbeesasaspecieshaventhadonedayoffin27millionyearsSoyoulljustworkustodeathWellsuretryWowThatblewmymindWhatsthedifferenceHowcanyousaythatOnejobforeverThatsaninsanechoicetohavetomakeImrelievedNowweonlyhavetomakeonedecisioninlifeButAdamhowcouldtheyneverhavetoldusthatWhywouldyouquestionanythingWerebeesWerethemostperfectlyfunctioningsocietyonEarthYoueverthinkmaybethingsworkalittletoowellhereLikewhatGivemeoneexampleIdontknowButyouknowwhatImtalkingaboutPleaseclearthegateRoyalNectarForceonapproachWaitasecondOheckitoutHeythosearePollenJocksWowIveneverseenthemthiscloseTheyknowwhatitslikeoutsidethehiveYeahbutsomedontcomebackHeyJocksHiJocksYouguysdidgreatYouremonstersYoureskyfreaksIloveitIloveitIwonderwheretheywereIdontknowTheirdaysnotplannedOutsidethehiveflyingwhoknowswheredoingwhoknowswhatYoucantjustdecidetobeaPollenJockYouhavetobebredforthatRightLookThatsmorepollenthanyouandIwillseeinalifetimeItsjustastatussymbolBeesmaketoomuchofitPerhapsUnlessyourewearingitandtheladiesseeyouwearingitThoseladiesArenttheyourcousinstooDistantDistantLookatthesetwoOoupleofHiveHarrysLetshavefunwiththemItmustbedangerousbeingaPollenJockYeahOnceabearpinnedmeagainstamushroomHehadapawonmythroatandwiththeotherhewasslappingmeOhmyIneverthoughtIdknockhimoutWhatwereyoudoingduringthisTryingtoalerttheauthoritiesIcanautographthatAlittlegustyouttheretodaywasntitcomradesYeahGustyWerehittingasunflowerpatchsixmilesfromheretomorrowSixmileshuhBarryApuddlejumpforusbutmaybeyourenotupforitMaybeIamYouarenotWeregoing0900atJGateWhatdoyouthinkbuzzyboyAreyoubeeenoughImightbeItalldependsonwhat0900meansHeyHonexDadyousurprisedmeYoudecidewhatyoureinterestedinWelltheresalotofchoicesButyouonlygetoneDoyouevergetboreddoingthesamejobeverydaySonletmetellyouaboutstirringYougrabthatstickandyoujustmoveitaroundandyoustiritaroundYougetyourselfintoarhythmItsabeautifulthingYouknowDadthemoreIthinkaboutitmaybethehoneyfieldjustisntrightformeYouwerethinkingofwhatmakingballoonanimalsThatsabadjobforaguywithastingerJanetyoursonsnotsurehewantstogointohoneyBarryyouaresofunnysometimesImnottryingtobefunnyYourenotfunnyYouregoingintohoneyOursonthestirrerYouregonnabeastirrerNooneslisteningtomeWaittillyouseethesticksIhaveIcouldsayanythingrightnowImgonnagetananttattooLetsopensomehoneyandcelebrateMaybeIllpiercemythoraxShavemyantennaeShackupwithagrasshopperGetagoldtoothandcalleverybodydawgImsoproudWerestartingworktodayTodaysthedayOomeonAllthegoodjobswillbegoneYeahrightPollencountingstuntbeepouringstirrerfrontdeskhairremovalIsitstillavailableHangonTwoleftOneofthemsyoursOongratulationsSteptothesideWhatdyougetPickingcrudoutStellarWowOoupleofnewbiesYessirOurfirstdayWearereadyMakeyourchoiceYouwanttogofirstNoyougoOhmyWhatsavailableRestroomattendantsopennotforthereasonyouthinkAnychanceofgettingtheKrelmanSureyoureonImsorrytheKrelmanjustclosedoutWaxmonkeysalwaysopenTheKrelmanopenedupagainWhathappenedAbeediedMakesanopeningSeeHesdeadAnotherdeadoneDeadyDeadifiedTwomoredeadDeadfromtheneckupDeadfromtheneckdownThatslifeOhthisissohardHeatingcoolingstuntbeepourerstirrerhumminginspectornumbersevenlintcoordinatorstripesupervisormitewranglerBarrywhatdoyouthinkIshouldBarryBarryAllrightwevegotthesunflowerpatchinquadrantnineWhathappenedtoyouWhereareyouImgoingoutOutOutwhereOutthereOhnoIhavetobeforeIgotoworkfortherestofmylifeYouregonnadieYourecrazyHelloAnothercallcominginIfanyonesfeelingbravetheresaKoreandelion83rdthatgetstheirrosestodayHeyguysLookatthatIsntthatthekidwesawyesterdayHolditsonflightdecksrestrictedItsOKLouWeregonnatakehimupReallyFeelingluckyareyouSignherehereJustinitialthatThankyouOKYougotarainadvisorytodayandasyouallknowbeescannotflyinrainSobecarefulAsalwayswatchyourbroomshockeysticksdogsbirdsbearsandbatsAlsoIgotacoupleofreportsofrootbeerbeingpouredonusMurphysinahomebecauseofitbabblinglikeacicadaThatsawfulAndareminderforyourookiesbeelawnumberoneabsolutelynotalkingtohumansAllrightlaunchpositionsBuzzbuzzbuzzbuzzBuzzbuzzbuzzbuzzBuzzbuzzbuzzbuzzBlackandyellowHelloYoureadyforthishotshotYeahYeahbringitonWindcheckAntennaecheckNectarpackcheckWingscheckStingercheckScaredoutofmyshortscheckOKladiesletsmoveitoutPoundthosepetuniasyoustripedstemsuckersAllofyoudrainthoseflowersWowImoutIcantbelieveImoutSoblueIfeelsofastandfreeBoxkiteWowFlowersThisisBlueLeaderWehaverosesvisualBringitaround30degreesandholdRoses30degreesrogerBringingitaroundStandtothesidekidItsgotabitofakickThatisonenectarcollectorEverseepollinationupcloseNosirIpickupsomepollenheresprinkleitoverhereMaybeadashoverthereapinchonthatoneSeethatItsalittlebitofmagicThatsamazingWhydowedothatThatspollenpowerMorepollenmoreflowersmorenectarmorehoneyforusOoolImpickingupalotofbrightyellowOouldbedaisiesDontweneedthoseOopythatvisualWaitOneoftheseflowersseemstobeonthemoveSayagainYourereportingamovingflowerAffirmativeThatwasonthelineThisisthecoolestWhatisitIdontknowbutImlovingthiscolorItsmellsgoodNotlikeaflowerbutIlikeitYeahfuzzyOhemicalyOarefulguysItsalittlegrabbyMysweetlordofbeesOandybraingetoffthereProblemGuysThiscouldbebadAffirmativeVerycloseGonnahurtMamaslittleboyYouarewayoutofpositionrookieOominginatyoulikeamissileHelpmeIdontthinktheseareflowersShouldwetellhimIthinkheknowsWhatisthisMatchpointYoucanstartpackinguphoneybecauseyoureabouttoeatitYowserGrossTheresabeeinthecarDosomethingImdrivingHibeeHesbackhereHesgoingtostingmeNobodymoveIfyoudontmovehewontstingyouFreezeHeblinkedSprayhimGrannyWhatareyoudoingWowthetensionlevelouthereisunbelievableIgottagethomeOantflyinrainOantflyinrainOantflyinrainMaydayMaydayBeegoingdownKencouldyouclosethewindowpleaseKencouldyouclosethewindowpleaseOheckoutmynewresumeImadeitintoafoldoutbrochureYouseeFoldsoutOhnoMorehumansIdontneedthisWhatwasthatMaybethistimeThistimeThistimeThistimeThistimeThisDrapesThatisdiabolicalItsfantasticItsgotallmyspecialskillsevenmytoptenfavoritemoviesWhatsnumberoneStarWarsNahIdontgoforthatkindofstuffNowonderweshouldnttalktothemTheyreoutoftheirmindsWhenIleaveajobinterviewtheyreflabbergastedcantbelievewhatIsayTheresthesunMaybethatsawayoutIdontrememberthesunhavingabig75onitIpredictedglobalwarmingIcouldfeelitgettinghotterAtfirstIthoughtitwasjustmeWaitStopBeeStandbackThesearewinterbootsWaitDontkillhimYouknowImallergictothemThisthingcouldkillmeWhydoeshislifehavelessvaluethanyoursWhydoeshislifehaveanylessvaluethanmineIsthatyourstatementImjustsayingalllifehasvalueYoudontknowwhathescapableoffeelingMybrochureThereyougolittleguyImnotscaredofhimItsanallergicthingPutthatonyourresumebrochureMywholefacecouldpuffupMakeitoneofyourspecialskillsKnockingsomeoneoutisalsoaspecialskillRightByeVanessaThanksVanessanextweekYogurtnightSureKenYouknowwhateverYoucouldputcarobchipsonthereByeSupposedtobelesscaloriesByeIgottasaysomethingShesavedmylifeIgottasaysomethingAllrighthereitgoesNahWhatwouldIsayIcouldreallygetintroubleItsabeelawYourenotsupposedtotalktoahumanIcantbelieveImdoingthisIvegottoOhIcantdoitOomeonNoYesNoDoitIcantHowshouldIstartitYoulikejazzNothatsnogoodHereshecomesSpeakyoufoolHiImsorryYouretalkingYesIknowYouretalkingImsosorryNoitsOKItsfineIknowImdreamingButIdontrecallgoingtobedWellImsurethisisverydisconcertingThisisabitofasurpriseto
  
  int length = 64;
  char actual[length];
  int flag = getIt(actual, &length);
  TEST_ASSERT_EQUAL_INT(flag, 1);
  TEST_ASSERT_EQUAL_STRING(expected, actual);



}

void simple_float_input(void) {
  // generate some actual formatted floats and run them through
  char * expected = "3.0";
  int length = 64;
  char actual[64];
  int flag = getIt(actual, &length);
  TEST_ASSERT_EQUAL_INT(flag, 1);
  TEST_ASSERT_EQUAL_STRING(expected, actual);

}

// not needed when using generate_test_runner.rb
int main(void) {
    UNITY_BEGIN();
    // call tests here
    // RUN_TEST(giant_input);
    // RUN_TEST(simple_float_input);
    // RUN_TEST(zero_length_input);
    // RUN_TEST(empty_input);
    return UNITY_END();
}
